services:
  test-runner:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    working_dir: /src
    volumes:
      - .:/src
    environment:
      - FF_ADVANCED_STATS=true
    command: dotnet test
    depends_on:
      - api
    networks:
      - robot-network

networks:
  robot-network:
    driver: bridge